/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        canvas: "#0a0a0b",
        panel: "#0f0f12",
        "panel-2": "#15161a",
        "panel-3": "#1c1d22",
        "border-soft": "#1f2024",
        "border-strong": "#2a2c33",
        ink: "#e8e9ed",
        "ink-2": "#9b9da8",
        "ink-3": "#5b5d68",
        accent: "#00d4aa",
        "accent-soft": "rgba(0,212,170,0.12)",
        "accent-strong": "#00b894",
        warn: "#f59e0b",
        critical: "#ef4444",
        good: "#10b981",
        amber: {
          500: "#f59e0b",
        },
        op: {
          bg: "#0a0a0b",
          panel: "#0f0f12",
          panel2: "#15161a",
          panel3: "#1c1d22",
          border: "#1f2024",
          borderStrong: "#2a2c33",
          ink: "#e8e9ed",
          ink2: "#9b9da8",
          ink3: "#5b5d68",
          accent: "#00d4aa",
          accentSoft: "rgba(0,212,170,0.12)",
          warn: "#f59e0b",
          danger: "#ef4444",
          good: "#10b981",
        },
      },
      fontFamily: {
        sans: [
          "Inter",
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          "Segoe UI",
          "Roboto",
          "sans-serif",
        ],
        mono: [
          '"IBM Plex Mono"',
          '"JetBrains Mono"',
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Consolas",
          "monospace",
        ],
        serif: [
          "Newsreader",
          '"Source Serif Pro"',
          "Georgia",
          "serif",
        ],
      },
      fontSize: {
        micro: ["10px", { lineHeight: "14px", letterSpacing: "0.06em" }],
        meta: ["11px", { lineHeight: "16px" }],
      },
      letterSpacing: {
        tighter: "-0.025em",
        wider: "0.06em",
      },
      borderRadius: {
        DEFAULT: "4px",
        sm: "3px",
        md: "6px",
        lg: "8px",
      },
      boxShadow: {
        panel: "0 1px 0 0 rgba(148,163,184,0.04) inset",
      },
    },
  },
  plugins: [],
};
